# Generated by Django 6.0.2 on 2026-03-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_bio_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('karigar', 'Karigar')], default='customer', max_length=20),
        ),
    ]
