# Generated by Django 6.0.2 on 2026-03-11 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='karigar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='karigarprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('karigar', 'Karigar / Worker')], default='customer', max_length=20),
        ),
    ]
