# Generated by Django 6.0.2 on 2026-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_servicecategory_remove_karigarprofile_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bargain_message',
            field=models.TextField(blank=True, help_text='Latest bargain message', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bargain_status',
            field=models.CharField(choices=[('none', 'None'), ('customer_offered', 'Customer Offered'), ('karigar_countered', 'Karigar Countered'), ('agreed', 'Agreed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='counter_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Karigar's counter offer rate", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed rate', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='karigar_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Karigar's listed hourly rate at time of booking", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, help_text='Customer note to karigar', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='offered_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's offered rate", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('bargaining', 'Bargaining'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
