# Generated by Django 6.0.2 on 2026-03-15 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_booking_bargain_message_booking_bargain_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarigarApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('citizenship_number', models.CharField(max_length=50)),
                ('citizenship_front', models.ImageField(upload_to='applications/citizenship/')),
                ('citizenship_back', models.ImageField(blank=True, null=True, upload_to='applications/citizenship/')),
                ('service_title', models.CharField(max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='applications/certificates/')),
                ('work_sample', models.ImageField(blank=True, null=True, upload_to='applications/samples/')),
                ('about_yourself', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('service_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.servicecategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karigar_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
