# Generated by Django 6.0.2 on 2026-03-16 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_karigarapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_application', 'New Karigar Application'), ('new_booking', 'New Booking'), ('new_user', 'New User Registered'), ('review_posted', 'New Review Posted'), ('booking_complete', 'Booking Completed'), ('report', 'User Report')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Frontend route to navigate to, e.g. /admin-dashboard', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ref_user_id', models.IntegerField(blank=True, null=True)),
                ('ref_booking_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='ban_date',
            field=models.DateTimeField(blank=True, help_text='When the account was banned', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason given by admin when banning this account', null=True),
        ),
    ]
